### PR TITLE
Gd extension test

### PR DESCRIPTION
**Pull request by feefladder**
GUT for 4.0 branch

### CODE REVIEW

**Comment by 2shady4u** [comment]
Hey @feefladder 😄 

I see you are having with Github Actions :)
Just a small tip:
You can install Docker and create your own local images on which you can test everything yourself :)
In that way you don't have to wait 5 minutes every time to see that Github Action failed 😢

**Comment by 2shady4u** [comment]
Another tip:
To stop this video card driver issue you would have to use the "headless" version of Godot instead

**Comment by feefladder** [comment]
Thanks for the tip! I have docker, but didn't find a way to run github actions locally, could you give a hint/link to a tutorial?

**Comment by 2shady4u** [comment]
> Thanks for the tip! I have docker, but didn't find a way to run github actions locally, could you give a hint/link to a tutorial? EDIT: found it! https://github.com/nektos/act

Yes, Nektos is one way to do it 😄

**Comment by feefladder** [comment]
But how do you then run actions like checkout@v3 or something?

**Comment by 2shady4u** [comment]
> But how do you then run actions like checkout@v3 or something?

That would just be `git clone` 😄 
In most cases its your self-defined steps that fail and that need extensive debugging

**Comment by feefladder** [comment]
@2shady4u It's working now for mac and Ubuntu. In Windows I cuold not get wget command to work, but I think you'll know an easy solution to thins?

**Comment by 2shady4u** [comment]
Hi @feefladder 
Using modern PowerShell (Invoke-WebRequest) would be best imo:
https://adamtheautomator.com/powershell-download-file/

**Pull request closed without merging**
