### PR TITLE
Update GDExtension code to match beta-9 renames from godot-cpp

### PR DESCRIPTION
**Pull request by cridenour**

### CODE REVIEW

**Comment by cridenour** [comment]
Setting to draft as Godot reported all good with the initial launch, but silently fails when using the extension class.

**Comment by cridenour** [comment]
Removing draft as the error I'm seeing is only on my own project.

**Comment by cridenour** [comment]
In case anyone else has issues, if SQLite won't show up in the class documentation (F1) inside Godot after upgrading, you just need to nuke your `.godot` folder to fix. 

Also just a good habit for all Godot 4 upgrades.

**Comment by 2shady4u** [comment]
Thank you for updating this @cridenour 😄

**Pull request merged**
