### PR TITLE
bump to beta 14

### PR DESCRIPTION
**Pull request by Dfred**
beta 14

### CODE REVIEW

**Comment by 2shady4u** [comment]
Hi @cridenour!

As always: Thank you for updating! 😄

**Comment by Dfred** [comment]
> Hi @cridenour!
> 
> As always: Thank you for updating! smile

@2shady4u haha, I'm not cridenour, I'm DFred :) or maybe I missed something ? :D

**Comment by 2shady4u** [comment]
How embarrassing! 😬 
Sorry, @Dfred I've gotten so used to cridenour opening PRs for beta updates that my sleepy brain didn't register that it was you instead 😄 

Thank you for the update @Dfred 😆

**Comment by cridenour** [comment]
Haha sorry to drop the ball. I'm preparing to release a demo during Steam Next Fest so I locked myself on beta 12 unless playtesting brings out a bug. 😄

**Comment by 2shady4u** [comment]
How exciting! 😄
Be sure to post a link somewhere 🙂

**Comment by cridenour** [comment]
> How exciting! 😄 Be sure to post a link somewhere 🙂

It's now Godot famous!
https://godotengine.org/article/dev-snapshot-godot-4-0-beta-17/


And steam page here: https://store.steampowered.com/app/2159650/Drift/

**Pull request merged**
