### PR TITLE
Update build system to beta3.

### PR DESCRIPTION
**Pull request by cridenour**
Updates our Sconstruct to account for scons changes in godot-cpp. 

Could also change the logic to remove the new target names to match the old.

### CODE REVIEW

**Comment by cridenour** [comment]
Noticed a second period in this, don't merge :)

**Comment by cridenour** [comment]
Now working as intended.

**Review by 2shady4u — COMMENTED** [review]
Hi @cridenour!

This looks good to me 😄 
Would it be possible to squash your commits so I can merge this?

**Comment by cridenour** [comment]
@2shady4u done!

**Comment by 2shady4u** [comment]
Thanks!

**Pull request merged**
